# This workflow builds PyInstaller single-file executables
# of Meerk40t for Windows, (and hopefully) Linux, Mac

name: Meerk40t

on:
  release:
    types: [published]

jobs:
  build-centos7:
    runs-on: centos7
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2
    
    - name: Ensure latest meerk40t-camera
      run: |
        pip3 install meerk40t-camera opencv-python-headless

    - name: Build Meerk40t
      run: |
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/linux/meerk40t.spec
        mv mk40t.py meerk40t.py
        mv dist/MeerK40t dist/MeerK40t-centos7-glibc2.17

    - name: Upload Release Assets
      id: release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t-centos7-glibc2.17

       
  build-ubuntu:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install libgtk-3-dev
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller wheel
        pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Build meerk40t
      run: |
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t mk40t.py
        mv mk40t.py meerk40t.py
        mv dist/meerk40t dist/MeerK40t-Ubuntu-Latest

# Switched to using softprops/action-gh-release@v1
# because it supports uploading to existing release based on current tag.
    - name: Upload Release Assets
      id: release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t-Ubuntu-Latest


  build-windows:
    if: ${{ false }}
    runs-on: windows-latest
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x86'
# Yikes. ch341dll.dll is not compatible with 64-bit python/pyinstaller/ctypes
#
# Python 3.7, wxPython 4.0.7-post2 is specifically chosen to workaround
# issue meerk40t/meerk40t#242, once the SetLocale issue is resolved, we can test
# newer versions again. Python 3.8 is latest possible for Windows 7 support.

    - name: Install dependencies
      run: |
        pip install wheel
        pip install wxPython==4.0.7-post2
        pip install meerk40t-camera ezdxf opencv-python-headless

# Compile bootloaders in order to reduce virus totals
# PYTHONHASHSEED is an attempt to get deterministic builds for VirusTotal
    - name: Build pyinstaller, generate bootloaders
      env:
        PYTHONHASHSEED: 12506
      run: |
        git clone --depth=1 https://github.com/pyinstaller/pyinstaller
        cd pyinstaller/bootloader
        python3 ./waf distclean all --target-arch=32bit
        cd ..
        python3 setup.py install
        cd ..

    - name: Build MeerK40t (wxPython 4.0.7-post2)
      run: |
        move meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/win/meerk40t.spec
        move mk40t.py meerk40t.py
        move dist/meerk40t.exe dist/wx-meerk40t.exe

    - name: Build MeerK40t (wxPython 4.1.1)
      run: |
        pip install wxPython==4.1.1
        move meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/win/meerk40t.spec
        move mk40t.py meerk40t.py
        move dist/meerk40t.exe dist/MeerK40t.exe

# Switched to using softprops/action-gh-release@v1
# because it supports uploading to existing release based on current tag.
    - name: Upload Release Assets
      id: release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          dist/MeerK40t.exe
          dist/wx-meerk40t.exe

