name: SefroCut (Macintosh)
##Options for VM
##macos-10.15 or macos-latest
##macos-11
##
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-macos11:
    runs-on: macos-11
    steps:
    - name: Checkout sefrocut
      uses: actions/checkout@v4
##    - name: Set up Python 3.9
##      uses: actions/setup-python@v5
##      with:
##        python-version: 3.9
    - name: Alternative Python Install if needed
      run: |
        wget https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg
        sudo installer -pkg python-3.8.10-macosx10.9.pkg -target /
    - name: Install Mac dependencies
      run: |
        which curl
        python3 -V
        which wget
        which git
        which gcc
        which xcode-select
        which cmake
        which pkgbuild
        which productsign
        which plutil
        which codesign
        which xcrun
        which xcode-select
        ls
        git clone https://github.com/libusb/libusb.git
        cd libusb
        ./autogen.sh && ./configure && make && sudo make install
        cd ..
        curl --remote-name http://www.ijg.org/files/jpegsrc.v9c.tar.gz
        tar -zxvf jpegsrc.v9c.tar.gz
        cd jpeg-9c
        ./configure && make && sudo make install
        cd ..
        ## git clone https://github.com/numpy/numpy.git
        ## cd numpy
        ## python3.8 -m pip install .
        ## cd ..

    - name: Ensure latest pip and sefrocut-camera
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install wheel setuptools==65.5.1
        python3.8 -m pip install --no-use-pep517 pyinstaller==4.3
        python3.8 -m pip install numpy==1.23.5
        python3.8 -m pip install pyusb
        python3.8 -m pip install potracer
        python3.8 -m pip install pillow==9.5.0
        python3.8 -m pip install wxPython
        python3.8 -m pip install ezdxf
        python3.8 -m pip install pyserial
        python3.8 -m pip install bitarray
        python3.8 -m pip install scipy==1.10.0
        python3.8 -m pip install --use-pep517 pyclipr
        python3.8 -m pip install numba
        python3.8 -m pip install requests
        python3.8 -m pip install .
        python3.8 -m pip install sefrocut-camera opencv-python-headless==4.5.3.56
        python3.8 -m pip install sefrocut-barcodes

    - name: pip list
      run: |
          python3.8 -m pip list

    - name: Build sefrocut
      id: build
      run: |
        ## git clone https://github.com/sefrocut/sefrocut.git
        ## cd sefrocut
        ## git pull
        git clone https://github.com/ronaldoussoren/py2app.git
        cd py2app
        git checkout master
        git pull
        python3.8 -m pip install .
        cd ..
            ##Set bundle version
            ##Download the extra files here sefrocut.icns entitlements.plist setup_mac.py
            ##May need to compare extras_required vs. current version of setup.py
            ##Unpack inside the sefrocut directory
        cp .github/workflows/mac/setup_mac.py setup_mac.py
        cp .github/workflows/mac/entitlements.plist entitlements.plist
        cp .github/workflows/mac/sefrocut.icns sefrocut.icns
        cp .github/workflows/mac/libusb-1.0.dylib libusb-1.0.dylib
        VERSION=$(python3.8 sefrocut.py -V)
        MKVERSION=$(echo $VERSION | cut -d" " -f 2)
        sed -i "" "s|0.0.0|$MKVERSION|g" setup_mac.py

        ## Export env variable to github actions scope to use in tag_name of upload release
        ## echo "::set-output name=mkversion::$(echo $MKVERSION)"
        echo "mkversion=$(echo $MKVERSION)" >> $GITHUB_OUTPUT
        ## python3.8 setup_mac.py py2app --dylib-excludes /usr/local/lib/libssl.1.1.dylib,/usr/local/lib/libcrypto.1.1.dylib,/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PIL/.dylibs/libfreetype.6.dylib,/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/PIL/.dylibs/liblzma.5.dylib --frameworks libusb-1.0.dylib
        mv sefrocut.py mk40t.py
        python3.8 -m PyInstaller --hidden-import wx._adv --hidden-import wx._xml --hidden-import sefrocut --windowed --noconfirm -i sefrocut.icns --add-data 'locale/:locale/' --name SefroCut mk40t.py
        mv mk40t.py sefrocut.py
        rm -rf dist/SefroCut
        sed -i "" "s|$MKVERSION|0.0.0|g" setup_mac.py
        ## Backwards compatibility
        rm dist/SefroCut.app/Contents/MacOS/libusb-1.0.dylib
        cp libusb-1.0.dylib dist/SefroCut.app/Contents/MacOS/libusb-1.0.dylib
        ## plutil -insert NSRequiresAquaSystemAppearance -bool NO dist/sefrocut.app/Contents/Info.plist
        plutil -insert NSRequiresAquaSystemAppearance -bool NO dist/sefrocut.app/Contents/Info.plist
        plutil -insert CFBundleDevelopmentRegion -string en dist/sefrocut.app/Contents/Info.plist
        plutil -insert CFAppleHelpAnchor -string YES dist/sefrocut.app/Contents/Info.plist
        plutil -replace CFBundleIdentifier -string org.tatarize.SefroCut dist/sefrocut.app/Contents/Info.plist
        plutil -replace CFBundleShortVersionString -string $MKVERSION dist/sefrocut.app/Contents/Info.plist
        plutil -insert CFBundleSupportedPlatforms -string MacOSX dist/sefrocut.app/Contents/Info.plist
        ## plutil -insert CFBundleTypeExtensions -string "*" dist/sefrocut.app/Contents/Info.plist
        plutil -insert CFBundleTypeRole -string Editor dist/sefrocut.app/Contents/Info.plist
        plutil -insert CFBundleVersion -string $MKVERSION dist/sefrocut.app/Contents/Info.plist
        plutil -insert LSApplicationCategoryType -string public.app-category.utilities dist/sefrocut.app/Contents/Info.plist
        ## plutil -insert LSFileQuarantineEnabled -string YES dist/sefrocut.app/Contents/Info.plist
        ## plutil -insert NSAppleScriptEnabled -bool NO dist/sefrocut.app/Contents/Info.plist
        plutil -insert NSHumanReadableCopyright -string "Copyright Â© 2019-2021 SefroCut Developers, MIT License" dist/sefrocut.app/Contents/Info.plist

        ## plutil -insert  -string  dist/sefrocut.app/Contents/Info.plist
        ## plutil -replace  -string  dist/sefrocut.app/Contents/Info.plist
        SIG="-"
        plutil -replace CFBundleSupportedPlatforms -xml "<array><string>MacOSX</string></array>" dist/SefroCut.app/Contents/Info.plist

        ## Fix the numpy 32 bit issue inside the app bundle - or install numpy from source.
        ## lipo dist/SefroCut.app/Contents/MacOS/libgcc_s.1.dylib -remove i386 -output dist/SefroCut.app/Contents/MacOS/libgcc_s_new.1.dylib
        ## rm dist/SefroCut.app/Contents/MacOS/libgcc_s.1.dylib
        ## mv dist/SefroCut.app/Contents/MacOS/libgcc_s_new.1.dylib dist/SefroCut.app/Contents/MacOS/libgcc_s.1.dylib

        echo "Codesign for GITHUB"
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/*.zip

        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/wx/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/Python
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/PIL/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/numpy/random/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/numpy/linalg/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/numpy/fft/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/numpy/core/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/lib-dynload/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/ezdxf/acc/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/cv2/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/*.dylib
        ## codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/*.so
        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app/Contents/MacOS/SefroCut

        codesign -s $SIG --force --verbose=4 --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/SefroCut.app
        ## codesign -s $SIG --deep --timestamp --entitlements entitlements.plist -i org.tatarize.SefroCut -o runtime --arch x86_64 dist/sefrocut.app

        echo "DMG Build..."
        hdiutil create -volname "SefroCut Mac" -srcfolder dist -ov SefroCut_unsigned.dmg
            ## GUI function check - Fails on runner (security settings).
        ## open dist/SefroCut.app
            ## Binary bundle CLI function check - Fails on runner (security settings).
        ##. dist/SefroCut.app/Contents/MacOS/SefroCut -V
            ##I don't do this part; mv dist/sefrocut dist/SefroCut-Ubuntu-Latest

    - name: Directory contents
      run: |
        cd ..
        ls
        cd ..
        ls

# Switched to using softprops/action-gh-release@v1
# because it supports uploading to existing release based on current tag.
    - name: Upload Release Assets
      id: release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          SefroCut_unsigned.dmg
